CREATE DATABASE IF NOT EXISTS COP4331;
USE COP4331;

CREATE USER IF NOT EXISTS 'TheBeast'@'%' IDENTIFIED BY 'WeLoveCOP4331';
GRANT ALL PRIVILEGES ON COP4331.* TO 'TheBeast'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS Users (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(50),
  lastName VARCHAR(50),
  Login VARCHAR(50),
  Password VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS Colors (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT,
  Name VARCHAR(50)
);

INSERT INTO Users(firstName, lastName, Login, Password)
VALUES ('Test', 'User', 'testuser', 'testpass');

INSERT INTO Colors(UserID, Name)
VALUES (1, 'Blue');